
/*AGGREGATE FUNCTIONS*/
CREATE TABLE PRODUCTS(SI INT NOT NULL,SNAME VARCHAR(10),PRICE DECIMAL,QUANTITY INT);

INSERT INTO PRODUCTS VALUES(101,'LAPTOP',70000,59);
INSERT INTO PRODUCTS VALUES(102,'MOBILES',30000,67);
INSERT INTO PRODUCTS VALUES(103,'HEADPHONES',10000,34);
INSERT INTO PRODUCTS VALUES(104,'WATCH',35000,78);
INSERT INTO PRODUCTS VALUES(105,'TABS',40000,45);
INSERT INTO PRODUCTS VALUES(106,'SHOES',4000,90);
INSERT INTO PRODUCTS VALUES(107,'BAG',1500,67);
INSERT INTO PRODUCTS VALUES(108,'BUDS',6000,78);
/*COUNT*/
SELECT COUNT(QUANTITY) AS PRODUCTS_NO
FROM PRODUCTS
GROUP BY PRICE
HAVING PRICE>=20000;


/*AVG*/
SELECT AVG(PRICE) FROM PRODUCTS;
/*DISTINCT*/
SELECT DISTINCT(PRICE) FROM PRODUCTS;
/*MAX*/
SELECT MAX(PRICE) FROM PRODUCTS;
/*MIN*/
SELECT MIN(PRICE) FROM PRODUCTS;
/*SUM*/
SELECT SUM(QUANTITY) FROM PRODUCTS;

/*KEY CONSTRAINTS*/
/* PRIMARY KEY,UNIQUE,CHECK,DEFAULT,NOT NULL*/
CREATE TABLE DEMO(SI INT PRIMARY KEY,
SUB_NO INT UNIQUE,
AGE INT CHECK(AGE BETWEEN 18 AND 45),
SALARY DECIMAL DEFAULT 15000,
NAME VARCHAR(10) NOT NULL);
/*FOREIGN KEY*/
CREATE TABLE EMPLOYEE_NO(EMPLOYEE_ID INT NOT NULL, SUB_NO INT PRIMARY KEY FOREIGN KEY REFERENCES DEMO(SUB_NO));

/*PRODUCTS_DETAILS*/
CREATE TABLE PRODUCTS_DETAILS(SI INT NOT NULL, SNAME VARCHAR(10),PURCHASED_NO INT);

INSERT INTO PRODUCTS_DETAILS VALUES(101,'LAPTOP',34);
INSERT INTO PRODUCTS_DETAILS VALUES(102,'MOBILES',56);
INSERT INTO PRODUCTS_DETAILS VALUES(104,'WATCH',45);
INSERT INTO PRODUCTS_DETAILS VALUES(107,'BAGS',17);
INSERT INTO PRODUCTS_DETAILS VALUES(103,'HEADPHONES',23);
SELECT * FROM PRODUCTS;


/*INNER JOIN*/
SELECT PRODUCTS.SI, PRODUCTS.SNAME,PRODUCTS_DETAILS.PURCHASED_NO
FROM PRODUCTS
INNER JOIN PRODUCTS_DETAILS
ON PRODUCTS.SI = PRODUCTS_DETAILS.SI;


/*LEFT JOIN*/
SELECT PRODUCTS.SI, PRODUCTS.SNAME,PRODUCTS_DETAILS.PURCHASED_NO
FROM PRODUCTS
LEFT JOIN PRODUCTS_DETAILS
ON PRODUCTS.SI = PRODUCTS_DETAILS.SI;


/*RIGHT JOIN*/
SELECT PRODUCTS.SI, PRODUCTS.SNAME,PRODUCTS_DETAILS.PURCHASED_NO
FROM PRODUCTS
RIGHT JOIN PRODUCTS_DETAILS
ON PRODUCTS.SI = PRODUCTS_DETAILS.SI;

/*FULL OUTER JOIN*/
SELECT PRODUCTS.SI, PRODUCTS.SNAME,PRODUCTS_DETAILS.PURCHASED_NO
FROM PRODUCTS
FULL JOIN PRODUCTS_DETAILS
ON PRODUCTS.SI = PRODUCTS_DETAILS.SI;








/*ADDITION OPERATOR*/
SET NOCOUNT ON
DECLARE @STARTDATE DATETIME , @ADDDAYS INT;
SET @STARTDATE = 'JANUARY 1,2023 12:00 AM';
SET @ADDDAYS = 5;
SET NOCOUNT OFF;
SELECT @STARTDATE + 2.5 AS 'START DATE',
	@STARTDATE + @ADDDAYS + 6 AS 'DAYS';


/*SUBTRCTION OPERATOR*/
SELECT P.SI, P.SNAME, P.QUANTITY - D.PURCHASED_NO AS 'REMAINING_QUANTITY'
FROM PRODUCTS AS P
JOIN PRODUCTS_DETAILS AS D
ON P.SI = D.SI
ORDER BY 'REMAINING_QUANTITY' ASC;
