CREATE TABLE STUDENT(ID INT NOT NULL, NAME VARCHAR(10), CLASS INT, CITY VARCHAR(10));

INSERT INTO STUDENT VALUES (1, 'KAVYA', 3, 'DELHI');
INSERT INTO STUDENT VALUES (2, 'HINA', 6, 'HYD');
INSERT INTO STUDENT VALUES (3, 'MEGHA', 9, 'BNGLR');
INSERT INTO STUDENT VALUES (4, 'AISHA', 9, 'DELHI');


CREATE TABLE RECORDS(ID INT NOT NULL, CLASS INT, CITY VARCHAR(10));

INSERT INTO RECORDS VALUES (1, 5,'DELHI');
INSERT INTO RECORDS VALUES (2, 6 , 'BNGLR');
INSERT INTO RECORDS VALUES (3, 7, 'HYD');

/*EQUI JOIN*/
SELECT STUDENT.NAME, STUDENT.CLASS, RECORDS.CITY 
FROM STUDENT
JOIN RECORDS
ON STUDENT.CITY = RECORDS.CITY;

/*NON-EQUI JOIN*/
SELECT STUDENT.NAME, STUDENT.CLASS, RECORDS.CITY 
FROM STUDENT
JOIN RECORDS
ON STUDENT.CLASS >= RECORDS.CLASS;


/*SUB QUERY*/
SELECT STUDENT.NAME, STUDENT.CLASS, STUDENT.CITY
FROM STUDENT
WHERE STUDENT.CITY IN
(SELECT RECORDS.CITY FROM RECORDS WHERE RECORDS.CLASS=5);

UPDATE STUDENT
SET NAME='KUTTY' 
WHERE CITY IN
(SELECT CITY FROM RECORDS WHERE CLASS IN (5,6));

SELECT * FROM STUDENT;

/*EXISTS - SEARCHES FOR ATLEAST ONE RECORD IN SUB-QUERY*/
SELECT NAME 
FROM STUDENT
WHERE EXISTS
(SELECT CITY FROM RECORDS WHERE CITY='DELHI');

/*NOT EXISTS*/
SELECT NAME 
FROM STUDENT
WHERE NOT EXISTS
(SELECT CITY FROM RECORDS WHERE CLASS=5);

/*ANY - IF ATLEAST ONE RECORD IS PRESENT GIVES TRUE BOOLEAN VALUE*/
SELECT NAME 
FROM STUDENT
WHERE CITY= ANY
(SELECT CITY FROM RECORDS WHERE CITY='CHENNAI');

/*ALL- CHECKS IF ENTIRE COLUMN HAS THE SAME VALUE*/
SELECT NAME 
FROM STUDENT
WHERE CITY= ALL
(SELECT CITY FROM RECORDS WHERE CLASS='5');

/*SOME*/
SELECT NAME 
FROM STUDENT
WHERE CITY= SOME
(SELECT CITY FROM RECORDS WHERE CITY='CHENNAI');


/*IN*/
SELECT NAME FROM STUDENT
WHERE CITY IN( SELECT CITY FROM RECORDS WHERE ID=1);


/*NOT IN*/
SELECT NAME FROM STUDENT
WHERE CITY NOT IN (SELECT CITY FROM RECORDS WHERE ID=1);

