/*SET OPERATORS - MUST HAVE SAME NUMBER AND ORDER OF COLUMNS*/

CREATE TABLE T1_EMPLOYEES (
   ID INT NOT NULL,
   NAME VARCHAR (20) NOT NULL,
   DEPT VARCHAR(10),
   SALARY DECIMAL (18, 2),
   EXPERIENCE INT,
   PRIMARY KEY (ID)
);

INSERT INTO T1_EMPLOYEES (ID,NAME,DEPT,SALARY,EXPERIENCE) VALUES('1','AKASH','PHYSICS',25000.00,2);
INSERT INTO T1_EMPLOYEES (ID,NAME,DEPT,SALARY,EXPERIENCE) VALUES('2','ABHIRAM','MATHS',30000.00,3);
INSERT INTO T1_EMPLOYEES (ID,NAME,DEPT,SALARY,EXPERIENCE) VALUES('3','PRANAV','CHEMISTRY',25000.00,1);
INSERT INTO T1_EMPLOYEES (ID,NAME,DEPT,SALARY,EXPERIENCE) VALUES('4','SHUBMAN','CHEMISTRY',20000.00,0);
INSERT INTO T1_EMPLOYEES (ID,NAME,DEPT,SALARY,EXPERIENCE) VALUES('5','SHREYAS','MATHS',33000.00,8);
INSERT INTO T1_EMPLOYEES (ID,NAME,DEPT,SALARY,EXPERIENCE) VALUES('6','VIRAT','BIOLOGY',40000.00,7);
INSERT INTO T1_EMPLOYEES (ID,NAME,DEPT,SALARY,EXPERIENCE) VALUES('7','SACHIN','PHYSICS',45000.00,9);


CREATE TABLE T2_EMPLOYEES (
   IDI INT NOT NULL,
   NAMES VARCHAR (20) NOT NULL,
   DEPTT VARCHAR(10),
   SALARYY DECIMAL (18, 2),
   EXPERIENCEE INT,
   PRIMARY KEY (IDI)
);

INSERT INTO T2_EMPLOYEES VALUES ('1','ARJUN','R&D',34000.00,2);
INSERT INTO T2_EMPLOYEES VALUES ('2','PRASHANT','PRODUCTION',30000.00,3);
INSERT INTO T2_EMPLOYEES VALUES ('3','GAUTHAM','SALES',45000.00,5);
INSERT INTO T2_EMPLOYEES VALUES ('4','ABHISHEK','ACCONTS',50000.00,6);
INSERT INTO T2_EMPLOYEES VALUES ('5','RAHUL','MARKETING',32000.00,4);
INSERT INTO T2_EMPLOYEES VALUES ('6','SHUBH','R&D',56000.00,6);
INSERT INTO T2_EMPLOYEES VALUES ('7','ANAND','PRODUCTON',90000.00,7);

/*UNION STATEMENTS DELETES DUPLICATES ROWS IF AVAILABLE*/
SELECT * FROM T1_EMPLOYEES UNION SELECT * FROM T2_EMPLOYEES;

/*UNION ALL STATEMENTS DOESN'T DELETE DUPLICATE ROWS*/
SELECT * FROM T1_EMPLOYEES UNION ALL SELECT * FROM T2_EMPLOYEES;

INSERT INTO T2_EMPLOYEES VALUES('8','AKASH','PHYSICS',25000.00,2);
INSERT INTO T2_EMPLOYEES VALUES('9','ABHIRAM','MATHS',30000.00,3);
INSERT INTO T2_EMPLOYEES VALUES('10','PRANAV','CHEMISTRY',25000.00,1);

INSERT INTO T1_EMPLOYEES VALUES('11','AKASH','PHYSICS',25000.00,2);
INSERT INTO T1_EMPLOYEES VALUES('9','ABHIRAM','MATHS',30000.00,3);
INSERT INTO T1_EMPLOYEES VALUES('10','PRANAV','CHEMISTRY',25000.00,1);


/*INTERSECT STATEMENT */
SELECT * FROM T1_EMPLOYEES INTERSECT SELECT *FROM T2_EMPLOYEES;

SELECT * FROM T1_EMPLOYEES WHERE SALARY>=30000 INTERSECT SELECT * FROM T2_EMPLOYEES;

/*(MINUS) EXCEPT STATEMENT*/

SELECT * FROM T1_EMPLOYEES EXCEPT SELECT * FROM T2_EMPLOYEES;

SELECT * FROM T1_EMPLOYEES;
SELECT * FROM T2_EMPLOYEES;